version: '3.8'

services:
  app:
    build: .
    command: bash start.sh
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./downloads:/usr/src/app/downloads
      - ./tokens:/usr/src/app/tokens
      - ./accounts:/usr/src/app/accounts
      - ./rclone:/usr/src/app/rclone
      - ./thumbnails:/usr/src/app/thumbnails